name: CI - Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t aceest-fitness .

      # Debug step to verify files inside container
      - name: List files inside container
        run: docker run --rm aceest-fitness ls -R /app

      # Run tests inside container
      - name: Run Pytest inside container
        run: docker run --rm aceest-fitness
